version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:3000"
    depends_on: s
      - couchdb

  couchdb:
    container_name: couchdb
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
    
