version: '3'

services:
  app: 
    container_name: one2one_app
    restart: always
    build: . 
    ports:
      - '80:3000' # React Application on Port 80 on Host
      - '5000:5000' # CouchDB Application on Port 5000 on Host
    links: 
      - couch
    networks:
      - app_network

  couch:
    container_name: couch
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "9000:5984"
    environment:
      - COUCHDB_USER=SinsOnTwitter
      - COUCHDB_PASSWORD=group68
    networks:
      - app_network

networks:
  app_network:
    driver: bridge